language: csharp
solution: src/NParametrizer.sln
install:
  - nuget restore src/NParametrizer.sln
  - nuget install NUnit.Runners -Version 3.0.1 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Debug src/NParametrizer.sln
  - ls -l ./testrunner/NUnit.Console.3.0.1/tools
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./NParametrizer/src/NParametrizer.Tests/bin/Debug/NParametrizer.Tests.dll